### ISSUE TITLE
2.01 - version stated in both iati-activities and iati-activity

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Schemas#100]
Do we need both?

For storing activity blobs in datastore seems to make sense to have it on each activity. (We've discussed this somewhere before, haven't we?)

**Comment by Bjwebb** [comment]
This was discussed on GitHub at https://github.com/IATI/IATI-Schemas/issues/30 and following that discussion, I added a proposal to the Upgrades forum http://support.iatistandard.org/entries/50761977--version-should-be-consistent

Also adding a link, so I can find it later, to your separate issue for making `@version` mandatory https://github.com/IATI/IATI-Schemas/issues/101

**Comment by bill-anderson** [comment]
Definitely think we should add this to 2.01

I would rather create a new topic as @bjwebb your post is a tad confusing ...

"iati-activities/@version is required if iati-activity/@version is given" - suggests that it is not required if iati-activity/@version is not given

Suggest that both are mandatory and must be a valid version, not just a decimal

**Comment by Bjwebb** [comment]
"suggests that it is not required if iati-activity/@version is not given" - that is what I was proposing. Since your proposal is slightly different a new topic makes sense.

To be clear, I agree with making it mandatory, but that hadn't been suggested when I wrote my previous proposal.

**Comment by bill-anderson** [comment]
your suggestion is that it is okay for no version to be present?

I disagree. Up until now it has not been critical as everything is in theory compatible. Once we go to 2.01 this is a critical piece of data for users.

**Comment by Bjwebb** [comment]
Yes, you're quite right - I think my original proposal was trying to state as few constraints as possible to satisfy my specific use case. Additionally, we already state that `iati-activity/@version` is required if a later version than 1.0/1.01. (In practice most publishers don't use this, and use `iati-activities/@version` instead, which only had the "required if" text added in 1.04 https://github.com/IATI/IATI-Schemas/issues/21).

Definitely agree that my post is confusing, and that a new one should be written explicitly requiring `@version`.

As you say, for the datastore, it is important to have `@version` on `iati-activity`.

However, I also think it's important that data consumers are able to consider a whole file as being published to a particular version of the standard. This allows the whole file to be validated at once, and generally makes dealing with whole files easier. Having `@version` on `iati-activities` helps with this, and also makes it easier to compare versions across 2.01 and current files.

I would propose:
- `iati-activities/@version` is MANDATORY
- `iati-activity/@version` is MANDATORY
- All `@version` attributes in a given file must have the same value
- The value of `@version` must be on the version codelist https://github.com/IATI/IATI-Schemas/issues/101

As stated above, the biggest actual change for publishers is requiring `iati-activity/@version`, since very few currently use this.

**Comment by bill-anderson** [comment]
Agree with your proposal. I'm going to add it to http://support.iatistandard.org/entries/57972186-Version-2-01-Iteration-1-8-Miscellaneous

**Comment by Bjwebb** [comment]
Closing this issue, because the proposal has been added to the forum, and there's a new issue for implementing these changes https://github.com/IATI/IATI-Schemas/issues/109
