### ISSUE TITLE
2.01 - validating @version

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Schemas#101]
@version must now be mandatory and valid. How do we validate? Code list?

**Comment by Bjwebb** [comment]
A code list is probably the way to do this. I think makes sense for it to be a NonEmbedded list, since it would refer to multiple versions of the standard. (Unless you wanted a list specific to e.g. 2.01 on which the only value was `2.01`.)

Am I correct in thinking that the current list would be:
- 1.01
- 1.02
- 1.03

With 1.05/2.01 added when they are released?

**Comment by bill-anderson** [comment]
Yes, and the list could serve a dual purpose in linking to upgrade notes?

**Comment by Bjwebb** [comment]
Yes.

**Comment by Bjwebb** [comment]
For a wider issue around 2.01 changes to `@version` see https://github.com/IATI/IATI-Schemas/issues/109
