### ISSUE TITLE
Review all uses of mixed="true"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#112]
I think we should remove all these. Mixed data is more difficult for data users and it is not currently used by publishers. Removing all mixed data types would help enforce which elements should not contain text.

**Comment by davidmegginson** [comment]
I've reviewing the v1.04 branch (let me know if it's the wrong one).  Here's what I've found:

**iati-common.xsd:**

I think we should keep mixed content in _description_ so that people can embed (e.g.) HTML5 markup for some use cases.  It's OK to remove from the other elements and content types in this file, as long as we still allow _xsd:anyAttribute_ for all of them (so that people can add attributes from other namespaces).

**iati-activities-schema.xsd:**

Mixed content might make sense for _contact-info/mailing-address_ so that people could include more-sophisticated markup (e.g. parsing out different address elements). We could also make a case for _conditions/condition_ where embedded HTML5 or other markup might be useful in a longer description.  Otherwise, I think it's safe to remove mixed content.

(Side question: is indicatorOutcomeType actually used anywhere?)

**iati-organisations-schema.xsd:**

OK to remove mixed content from _name_

**iati-registry-record-schema.xsd:**

No mixed-content declarations in the file.

**Comment by Bjwebb** [comment]
@davidmegginson Thanks for taking the time to review this.

My proposal would be to remove mixed content everywhere, including the examples you mention. This is because whilst adding mixed content might be useful for some publishers to add extra information, it makes it rather difficult for data users to know how to handle the mixed content correctly, especially since it can contain any possible XML.

Instead, I would suggest that publishers provide a plain text version of the IATI fields (since they know how to make that transformation for their data), and also add the structured information as a new namespaced element. Version 2.01 will make this particularly nice to do for text, as you can have e.g. `description/narrative` and `description/mynamespace:html-narrative`. 

I also definitely agree that all elements should have xsd:anyAttribute.

(indicatorOutcomeType is not used anywhere, so we're removing it in 2.01 - https://github.com/IATI/IATI-Schemas/issues/129)
