### ISSUE TITLE
Contact Details - missing elements.

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#17]
In the forum post on this we have:

We have added the following:

Contact Type (with an associated code list)
Job Title
Website
The ability to report multiple languages has been added to:

Organisation Name
Person Name
Job Title
Mailing Address

.....

Looking at the 1.03 dev schema it looks to me as though:

1) Job title has been added, but Contact Type and Website have not

Also it seems that the elements are all of 'plainType' I think they should have been changed to 'textType' to enable multiple languages to be used as discussed above.

However, something I'm not clear on is the multilingual changes needed - is it
just changing the 'type=' bit?

**Comment by davidmegginson** [comment]
(Copied from the above commit)

Note that the Google spreadsheet called for the attribute name
"contact-type" rather than "type", but I used "type" for two reasons:
1. The "contact" in the name is redundant, since the attribute already
   appears in the "contact-info" element.
2. The use of "type" is consistent with other IATI elements.

**Comment by davidmegginson** [comment]
Changes complete.  Note that I didn't make non-textual child elements of contact-info (like contact-info/telephone) multilingual, and I used contact-info/@type rather than contact-info/@contact-type for consistency with the rest of the schema.

Over to @caprenter for review (with input from @bill-anderson).  Please check and close.

**Comment by caprenter** [comment]
Looks good to me. Thanks David. Leaving open for  @bill-anderson to check it meets his intentions.

**Comment by caprenter** [comment]
Assuming this is ok.
