### ISSUE TITLE
2.01 other identifier

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#228]
depending on outcome of this proposal, edit schemas accordingly

http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers

**Comment by Bjwebb** [comment]
As far as I can tell the required tasks for other identifier are:
- [x] Add the `@type` attribute to `other-identifier`
- [x] Add the `OtherIdentifierType` codelist https://github.com/IATI/IATI-Codelists/issues/67

**Comment by Bjwebb** [comment]
@bill-anderson Should the `@type` attribute on `other-identifier` be required?

**Comment by bill-anderson** [comment]
No.

I agree with Mark Brough's last response just posted at http://support.iatistandard.org/entries/52824355

I think in most of what I've seen so far, other-identifier has more often been used for internal project IDs rather than for linking to CRS reporting (though I may be wrong on this, it's just a vague impression)

If that's the case, I would suggest reversing A1 and A2, and to answer David's question, setting a default that if not specified, other-identifier would be assumed to be A1, internal project ID. _If we have a default then perhaps we can avoid making the attribute mandatory._

I think it's also cleaner to put internal project ID as A1 and the default, as all organisations should have some internal project ID whereas only some organisations will have CRS identifiers.

**Comment by stevieflow** [comment]
Just checking:

http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/other-identifier/

The `OtherIdentifierType` codelist doesnt seem to be cited.  `OrganisationIdentifier` seems to be....

**Comment by Bjwebb** [comment]
Good spot. This was a typo in the codelist mapping file. Should now be fixed.

**Comment by caprenter** [comment]
We have since agreed that the type attribute should be mandatory (reference?), so working on the commit...

**Comment by Bjwebb** [comment]
@bill-anderson Could you update the forum to explain that we making this change, and why?

http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers

**Comment by bill-anderson** [comment]
http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers?page=1#post_22478655

**Comment by bill-anderson** [comment]
see what i mean about what it looks like (which is far more scary-looking than it is)

**Comment by caprenter** [comment]
Now need to update the schema in line with this updated proposal:
http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers?page=1#post_22478655

**Comment by stevieflow** [comment]
FYI I've edited the example XML and code-example pages: https://github.com/IATI/IATI-Extra-Documentation/commit/5dfbf994774d4698fdd283cb95d307b3f14e2f88

**Comment by bill-anderson** [comment]
I've updated forum details in top section on http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers

**Comment by Bjwebb** [comment]
@bill-anderson That section does not say that we have added `other-identifier/@type` in 2.01. Should it?

**Comment by bill-anderson** [comment]
Does now
