### ISSUE TITLE
@type description

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#24]
The @type description, via the common/xsd is:

Free text describing the type of thing being referenced.

However, for instances such as organisation type or document type, we do wish that the code list is utilised.  Is this description therefore in need of a fix?

**Comment by bill-anderson** [comment]
Yes. 
"A coded attribute describing the type of entity described by the element, and defined by the relevant code list." Or something a little more coherent?

**Comment by caprenter** [comment]
Because this is in the iati-common schema it is meant to be re-used across many elements, hence the generic description.

If we want more specific information about certain elements or the way the attribute is used with those elements for now you will need to add it in the documentation on the wiki (which will be pulled into the website pages, but will not be in the schema itself)

If we want more useful descriptions within the schema we would need to think about how we did that.

This may be a suggestion for the next upgrade.

**Comment by stevieflow** [comment]
Yes, I realised that.  

My only thought was whether altering this generic case would fix our need in this version anyway?  The "generic text" is misleading publishers (perhaps). Is there an example of @type where it can be used in this way, or must @type also refer to a codelist?

**Comment by bill-anderson** [comment]
Always refers to a codelist

**Comment by Bjwebb** [comment]
This issue is discussed further in https://github.com/IATI/IATI-Standard-SSOT/issues/14 - I'm closing this issue now because the other one is more up to date.
