### ISSUE TITLE
Add new element: recipient-region-budget

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Schemas#283]
This issue is generated from the accepted version 2.02 proposal 'Org Standard - recipient-region-budget' vocabularies are used': http://support.iatistandard.org/entries/79323113-Org-Standard-recipient-region-budget

**Comment by bill-anderson** [comment]
Change the main description to:

The recipient-region-budget element allows for the reporting of forward looking budgets where the organisation maintains region-wide, rather than or in addition to country-specific budgets. The recommendation is that, where and when possible, the organisation’s total annual planned budget for each of the next three financial years is reported for each recipient region. This must NOT include an aggregation of budgets reported in the recipient-country-budget element. It is strongly recommended that publishers report to existing defined regions wherever possible.
