### ISSUE TITLE
Add new @aggregation-status attribute for the indicator element

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Schemas#363]
Add a new attribute at `iati-activities/iati-activity/result/indicator/@aggregation-status`, with the following definition:

> Boolean flag indicating whether the data in the result set are suitable for aggregation.

The attribute will have type `xsd:boolean` with occurrence rule `0..1`.

**Tasks:**

- [x] Add tests
- [x] Add `iati-activities/iati-activity/result/indicator/@aggregation-status`

**Comment by hayfield** [comment]
This is a boolean attribute and so should not be called `aggregation-status`. A boolean value should give an indication as to the direction of what `true` and `false` mean. This name does not.

A suggestion for an improved name is: `aggregatable`.

This clearly shows that a `true` value means the data can be aggregated, while a `false` value means it cannot.

---

This proposal for modification falls within the `The Community inspects and comments on the 2.03 changes on GitHub as they are being developed.` step of the [Upgrade Timetable](http://iatistandard.org/202/upgrades/decimal-upgrade-to-2-03/).

**Comment by andylolz** [comment]
It’s worth mentioning [`iati-activities/iati-activity/result/@aggregation-status`](http://iatistandard.org/104/activity-standard/iati-activities/iati-activity/result/#attributes). So it’s a choice between correctness and consistency.

NB I’m in no way affiliated with the `@aggregation-status` attribute. I wasn’t there for v1.01 when this was introduced. (In fact, this is my first IATI version upgrade.) I’m just pointing this out because it explains the choice by the proposer (@drmrsmith), and demonstrates the answer is perhaps not quite so clear-cut.

**Comment by hayfield** [comment]
> It’s worth mentioning iati-activities/iati-activity/result/@aggregation-status. So it’s a choice between correctness and consistency.

Bah!

Consistency it shall have to be, then... with a note to make sure it is not under any circumstances left unchanged with an integer (version 2 could have been so great... :( ).

**Comment by hayfield** [comment]
Since there is some argument for consistency, I will note my interpretation of meaning from the name...

Without reading the docs, the bad name `aggregation-status` naturally translates (in my head) to the actually-a-name-of-a-boolean `is-aggregated`.

This then means that:

* `true` reads as `This has been aggregated, treat it as such`
* `false` reads as `This has not been aggregated - you might want to aggregate it`

Which isn't quite the desired meaning!
Of course, upon closer inspection, the `false` definition is a bit nonsensical and so the next sensible step would be to read the docs and hope they can be made sense of.

The name, however... :(

**Comment by allthatilk** [comment]
If this question has been answered please note the resolution and remove the question label =)

**Comment by dalepotter** [comment]
Tagging @PetyaKangalova and @amy-silcock as there is a question here. From my reading, the consensus is that we should stick with the originally proposed name of `aggregation-status`.

**Comment by amy-silcock** [comment]
Agree that we should be consistent, so keep the name @aggregation-status.

Noting that at the next integer upgrade the name and description can be amended. @hayfield if there is a way of adding some guidance at this point do you want to take a look?

**Comment by hayfield** [comment]
@amy-silcock I'd suggest adding a thread in the relevant Discuss forum to note that changing the names to something appropriate is a required change for v3.

**Comment by stevieflow** [comment]
> Noting that at the next integer upgrade the name and description can be amended.
>  I'd suggest adding a thread in the relevant Discuss forum to note that changing the names to something appropriate is a required change for v3.

Here be dragons!  

``participating-org/@activity-id`` vs ``iati-identifier``vs ``related-activity/@ref`` anyone?

Or  ``participating-org/@ref`` vs ``organisation-identifier`` ?  

How about ``budget`` vs ``total-budget`` (with ``transaction/@type=[Commitment]`` also have a say) ?

The standard is riddled with these inconsistencies, I agree.  But, let's not always think "we can solve this in the next version", when so many people and organisations are desperately trying to use it as it stands

**Comment by hayfield** [comment]
> Here be dragons!

There are indeed (and as you note there are various problems with inconsistency as well as the this-is-flat-out-incorrect such as the attribute name in this PR).

If Standard is [to be usable](https://discuss.iatistandard.org/t/future-infrastructure-to-support-the-iati-standard/1047) beyond a very small group of people, they are issues that need resolving... and the first step is to note them down in one place.

**Comment by stevieflow** [comment]
> If Standard is to be usable beyond a very small group of people, they are issues that need resolving... and the first step is to note them down in one place.

Yes, agree.  As per the embedded / non-embedded stuff - listing and discussing can be good.  But - we can't also let the [perfect be the enemy of the good](https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good)

**Comment by andylolz** [comment]
> If Standard is to be usable beyond a very small group of people

I’d quite like these sorts of discrepancies and idiosyncrasies to be abstracted away, via some middleware. Then I just interact one layer up, and the middleware does the dirty work.

That’s the sort of thing pyIATI / the datastore could do for me, right?

I mean: Of course it would be nice to pull the weeds out at the root, but that’s not always straightforward. (I realise this attitude may be unpopular; I’m just trying to be pragmatic.)

**Comment by hayfield** [comment]
This is turning into a discussion about to the form of V3 and what IATI can become in the future.

As such I'd suggest having the conversation in a relevant location on [IATI Discuss](https://discuss.iatistandard.org/).

---

With the one specific question...

> That’s the sort of thing pyIATI / the datastore could do for me, right?

pyIATI: yes
Datastore: highly unlikely given likely resources and varied expectations

**Comment by andylolz** [comment]
> This is turning into a discussion about to the form of V3 and what IATI can become in the future.

Yeah, I nearly deleted my comment for that reason… but since the issue has the `complete` label anyway, I left it.

> Datastore: highly unlikely given likely resources and varied expectations

Sure – the “could” in my question was to illustrate it was more hypothetical. I.e. “a datastore” rather than “the datastore”. Or OIPA, for instance. I was more saying: We shouldn’t get too hung up on solving this at a very low level – it can be resolved at a higher level, and most users won’t know the difference.
