### ISSUE TITLE
language element describes code attribute, but not explicitly

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#62]
http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/document-link/language/

The schema description of the element:

> The ISO 639 language code for the target document, e.g. “en”.

Is actually describing the `@code` attribute. The text inside the element should actually be human readable text. The schema description should be updated to reflect this.

**Comment by caprenter** [comment]
I'm bumping this out of the 1.04 milestone as:

1) It may take time to agree a new description.
2) `@code` should be the value to pay attention to, and not any text information supplied, so maybe the description should reflect that.
3) It's not clear that the text should NOT be a language code (it could be)

So I think the issue should stay, but it is not crucial to have it fixed in 1.04

**Comment by Bjwebb** [comment]
I think this has been rectified in 2.01 http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/document-link/language/

The description of the element still refers to the language code, but the only possible content of the element is now the `@code` attribute, which now has it's own description making clear that's where the ISO 639-1 code belongs.
