### ISSUE TITLE
Add @vocabulary-version to location-id and administrative elements

### ISSUE THREAD

**Issue by owenscott** [IATI/IATI-Schemas#65]
Right now for each of these we have a code and vocabulary, e.g.

location-id
location-id/code
location-id/vocabulary

administrative
administrative/code
administrative/vocabulary

Suggesting to add location-id/vocabulary-version and administrative/vocabulary-version as well. For vocabularies which use explicit release versioning (e.g. GADM) it should record the version of the data which was used (to account for the risk  of changing administrative boundaries). For vocabularies which don't use explicit release versioning (e.g. OSM) it should record the date of access in ISO-date format. In the guidance notes we should make it clear and unambiguous which format to use for which vocabulary.

**Comment by Bjwebb** [comment]
I've linked to this issue from the relevant posts on the upgrade forum, so that it is visible to anyone following the proposals there:
- http://support.iatistandard.org/entries/30360498-New-Location-Location-Id-element?page=1#post_25385023
- http://support.iatistandard.org/entries/30855656-Changes-to-Location-Administrative-element?page=1#post_25403677

**Comment by Bjwebb** [comment]
Could you clarify what you mean by OSM lacking explicit release versioning? Each object seems to be both versioned individually, and each change is part of a globally numbered changeset.  Might one of these be preferable to an ISO-date?

**Comment by owenscott** [comment]
Let's chalk that one up to complete misremembering then :). If OSM has explicit versioning then we should definitely use that. In which case I think all of our vocabularies have versioning. I still suggest keeping ISO-DATE as a fallback option in the case of data sources like country-provided boundaries which we might support but which do not typically have explicit versioning.

**Comment by Bjwebb** [comment]
Following discussion with @caprenter and @bill-anderson we think that this proposal is best delayed until 1.05, since it is not completely necessary and it is quite late in the 1.04 process to be adding new elements/attributes.

I've created this forum post:
http://support.iatistandard.org/entries/53489706-Add-vocabulary-version-to-location-id-and-administrative-elements

**Comment by Bjwebb** [comment]
This is not in the 1.05 Upgrade, as 1.05 is now additions to codelists only.

**Comment by akmiller01** [comment]
Probably best to give different versioned vocabularies their own vocabulary code, rather than introducing a new vocabulary version attribute. Not sure if codes even need to be integers, necessarily, we could upgrade vocabulary codelists to have point codes for different version "1.1" "1.2" etc.
