### ISSUE TITLE
Implement 2.01 "Improvements to the Organisation Standard"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#69]
http://support.iatistandard.org/entries/45539933-Thematic-content-agreed-by-IATI-Steering-Committee

**Comment by Bjwebb** [comment]
@bill-anderson Could you please elaborate on what the proposed changes to the Organisation Standard are.

**Comment by bill-anderson** [comment]
Still needs work - I will get onto it next week

Sector budgets
And possibly the nesting of country budgets and country documents under a country element

@markbrough had some ideas - are they in KB?

**Comment by markbrough** [comment]
@bill-anderson - yes, all on the KB
- Country strategy papers: http://support.iatistandard.org/entries/21149511-document-link-and-country-strategy-papers
- Sectoral budgets: http://support.iatistandard.org/entries/21180586-Budgets-and-sectors
- Tentativeness of budgets: http://support.iatistandard.org/entries/21150501-Budgets-and-tentativeness

The third one I think is probably just a question of adding an optional attribute onto the relevant budget element, and creating a new `BudgetTentativeness` (or a better name...) codelist, which could be used both at organisation and activity level.

### Document links and budgets

For document-links and budgets, I guess you could either nest budgets under country or sector elements, or nest country/sector elements under budgets. I think the latter may make more sense because it would make it simpler to have more country/sector combinations. 

As we're looking at these elements, it struck me that adding `period-start` and `period-end` would be useful to describe the period of validity of the document (e.g. to find the latest annual report, or the currently applicable country strategy paper).

@theosande - you raised the need to support incoming funds at the organisation level. Could that be integrated within these changes to the budget element somehow?

Some examples below.

document-link:

``` xml
<document-link url="http://mysite.com/TZstrategy.doc" filetype="application/msword">
    <category code="B03">Country strategy paper</category>
    <title>Tanzania country strategy paper 2013-2015</title>
    <!-- New elements -->
    <recipient-country code="TZ">Tanzania</recipient-country>
    <period-start iso-date="2013-01-01"/>
    <period-end iso-date="2015-01-01"/>
</document-link>
```

document-link (2):

``` xml
<document-link url="http://mysite.com/evaluation.doc" filetype="application/msword">
    <category code="B10">Country Evaluation Report</category>
    <title>Tanzania education sector evaluation for 2011-2013</title>
    <!-- New elements -->
    <recipient-country code="TZ">Tanzania</recipient-country>
    <sector code="111" vocabulary="DAC-3">Education</sector>
    <period-start iso-date="2011-01-01"/>
    <period-end iso-date="2013-01-01"/>
</document-link>
```

budget:

``` xml
<!-- Rename from recipient-country-budget? What about total-budget? -->
<budget>
    <period-end iso-date="2014-01-01"/>
    <period-end iso-date="2015-01-01"/>
    <value currency="GBP">123000</value>
    <recipient-country code="TZ">Tanzania</recipient-country>
</budget>
```

budget (2):

``` xml
<budget>
    <period-end iso-date="2014-01-01"/>
    <period-end iso-date="2015-01-01"/>
    <value currency="GBP">456000</value>
    <!-- New element -->
    <sector code="111" vocabulary="DAC-3">Education</sector>
</budget>
```

**Comment by Bjwebb** [comment]
An organisation standard section has been added on the Knowledge Base - http://support.iatistandard.org/entries/57427467-Version-2-01-Iteration-1-6-Improvements-to-the-Organisation-Standard - this includes adding recipient-country to document-link and budget lines. Budget lines are proposed as a an alternative to sectoral budgets. There is a new GitHub issues for implementing these changes https://github.com/IATI/IATI-Schemas/issues/95

As for budget tentativeness, we think this should be made via a change to the BudgetType codelist in 1.05
