### ISSUE TITLE
Implement 2.01 "Recipient-region and recipient-country merge"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#71]
http://support.iatistandard.org/entries/41585486-Modify-recipient-country-and-recipient-region-merge-

http://support.iatistandard.org/entries/57972186-Version-2-01-Iteration-1-8-Miscellaneous
http://support.iatistandard.org/entries/77311697-Version-2-01-Iteration-2-8-Miscellaneous
- [x] 1) Allow for both existing elements to be used with the percentage split shared between them. (if both elements are used percentages must be reported and they should add up to 100% across all recipient- elements)
- [x] 2) Allow for the reporting of region and country at transaction as well as activity level
- [x] Current guidance advising use of only one or other of these elements should be reversed
- [x] recipient-region should only be used to indicate that the region as a whole is a recipient, not as an added description to a named recipient-country

**Comment by Bjwebb** [comment]
1) This is not enforced in any machine readable way at the moment, so this change will be a change to documentation text.
2) Is covered by https://github.com/IATI/IATI-Schemas/issues/70

**Comment by caprenter** [comment]
The outstanding tasks in this issue seem to me to be related to documentation and guidance, - working out what needs to be written and where that single source of truth lies (within the schema or not for example).

Assigning to @bill-anderson to create the words - taking into account opinions on the support forum - links above.

**Comment by bill-anderson** [comment]
- We do need a new rule that checks percentage split across recipient-country AND recipient-region.
- We can't enforce that recipient-region should not just describe the region in which a country occurs.

**Comment by bill-anderson** [comment]
recipient-country definition
A country that will benefit from this activity. If a specific country is not known the recipient-region element should be used instead. For geographical location, use the location element.  

Multiple countries and regions can be reported, in which case the percentage attribute MUST be used to specify the share of total commitments across all reported countries and regions. 

The country can also be specified at transaction rather than activity level. If transaction/recipient-country AND/OR transaction/recipient-region are used THEN ALL transaction elements MUST contain a recipient-country and/or recipient-region element AND iati-activity/recipient-region and iati-activity/recipient-region MUST NOT be used AND each transaction MUST only contain one recipient-country or recipient-region.

**Comment by bill-anderson** [comment]
recipient-region definition
A supranational geopolitical region that will benefit from this activity.  For sub-national geographical location, use the location element. 

Multiple countries and regions can be reported, in which case the percentage attribute MUST be used to specifiy the share of total commitments across all reported countries and regions. Recipient-region must not be used merely to describe the region of a country reported in recipient-region, but ONLY if the region is a recipient IN ADDITION to the country. 

Region can also be reported at transaction rather than activity level.  If transaction/recipient-country AND/OR transaction/recipient-region are used THEN ALL transaction elements MUST contain a recipient-country and/or recipient-region element AND iati-activity/recipient-region and iati-activity/recipient-region MUST NOT be used AND each transaction MUST only contain one recipient-country or recipient-region.

**Comment by stevieflow** [comment]
@bill-anderson is this guidance text, or also intended as schema description text?

**Comment by bill-anderson** [comment]
sorry, schema description

**Comment by Bjwebb** [comment]
Note that "iati-activuty" is a typo (also present in the current schema definition).

**Comment by bill-anderson** [comment]
@Bjwebb I've finished mods to above definitions which apply to activity- and transaction-levels. Definitions in org standard only need first para.

**Comment by Bjwebb** [comment]
I've updated the activity schema with your new definitions.

Actually I don't think most of the first paragraph is applicable to the definitions in the organisation standard. These currently are:

In recipient-country-budget:

> The recipient country.

In document-link:

> The recipient country that is the focus of the document. May be repeated for multiple countries.

I have left these as they are.
