### ISSUE TITLE
Documentlink example

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#74]
We state:

> The target URL of the external document, e.g. “http://www.example.org/doc.html”.

My understanding is that document-links are preferably documents to be downloaded, rather than webpages (which may contact several links)

@markbrough may have an opinion

In the schema description text (in org and activity) it might be worth adjusting to

a) reflect this

and/or

b) changing the URL to http://www.example.org/doc.odt

**Comment by markbrough** [comment]
@stevieflow I think that makes sense. In the 2014 Index we require that `document-link`s link to the specific document rather than a link to a general webpage that may (or may not) contain a relevant document for that activity.

I think it's still alright to link to webpages as long as they contain the relevant information, but I guess using a document as an example would be clearer (and I would just go for .docx rather than .odt as it's more recognisable).

**Comment by stevieflow** [comment]
Thanks @markbrough - 

Take a look at http://dev.iatistandard.org/organisation-standard/overview/document-links/ as an "overview" of documents - leading to the more detailed reference.

We should change the URL in the schema - I propose to keep the .odt though!

**Comment by Bjwebb** [comment]
a) In my mind, for a definition, "The target URL of the external document" says what we need it to. We say the URL of the document, not some URL of something that links to the document. Clarification of this may be useful, but should be in the Extra-Documentation.

b) I've changed the URL in the schema to what Steven suggested.

**Comment by Bjwebb** [comment]
I've split out the documentation issue to https://github.com/IATI/IATI-Extra-Documentation/issues/81
