### ISSUE TITLE
planned-disbursement is missing a description in the schema

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#82]
meaning that http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/planned-disbursement/ lacks any description

**Comment by Bjwebb** [comment]
Looking at Bill's spreadsheet - https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdDcwRHJxaXgtLWVoY2N5VWt4ck1oeGc&usp=drive_web#gid=1 - the 'definition' of planned disbursement is "The recommendation is that, where and when possible, the amounts it is planned to disburse and spend on the activity in each of the next three financial years are reported."

Not sure whether we should be using this definition, or a new one should be written.

**Comment by bill-anderson** [comment]
Needs a new one explaining difference between this and budgets

**Comment by bill-anderson** [comment]
From TAG - Clarifying Confusions
Budget
- The aim of the budget element is to provide forward looking data for planning purposes
- Annual or quarterly breakdowns of the total budget for the lifetime of the activity
- Budgets spanning periods greater than one year are invalid
- Changes to budgets should involvement replacement of data, not delta changes.

Planned Disbursement
- A further breakdown of the budget providing predictability of actual cash flow
- Particularly important for budget support
- Also useful for grant funding that has highly predictable disbursement dates
- (Problem in standard in accurately reporting a single date rather than a period – to be fixed in 1.05)

**Comment by Bjwebb** [comment]
`planned-disbursement` has a new description in 2.01:
https://github.com/IATI/IATI-Schemas/blob/bd94fa88d5bcbce53463bfcca36e5a0b603b1081/iati-activities-schema.xsd#L2011

Does this change resolve this issue, or is there more to do?

**Comment by stevieflow** [comment]
For 2.01 it resolves it.  

Question is whether we want to integrate anything into 1.04: http://iatistandard.org/activity-standard/iati-activities/iati-activity/planned-disbursement/

**Comment by caprenter** [comment]
@bill-anderson I think if we wanted to, we could probably make this change as part of 1.05. Is it a significant change or a clarification/bug fix?

**Comment by bill-anderson** [comment]
No problem in adding description change to 1.05
2.01 makes period-start (not period-end) conditionally mandatory, right?

**Comment by Bjwebb** [comment]
Yes - http://support.iatistandard.org/entries/77285258-Version-2-01-Iteration-2-2-Additional-Mandatory-Conditions

**Comment by caprenter** [comment]
I've added this proposal to the 1.05 upgrade forum here: http://support.iatistandard.org/entries/50424779-Add-a-description-in-the-schema-to-planned-disbursement-element
